# Generated by Django 6.0.4 on 2026-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_destino', models.CharField(default='5584994274111', max_length=20)),
                ('mensagem_template', models.TextField(default='Olá, meu nome é {nome} e realizei um orçamento pelo site.')),
                ('valor_base', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('quantidade', 'Quantidade'), ('prazo', 'Prazo'), ('modelo', 'Modelo'), ('estampa', 'Estampa'), ('tecido', 'Tecido'), ('adicional', 'Adicional')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, help_text='Emoji ou nome do ícone', max_length=50, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opção de Orçamento',
                'verbose_name_plural': 'Opções de Orçamento',
                'ordering': ['categoria', 'ordem', 'label'],
            },
        ),
    ]
