# Generated by Django 6.0.4 on 2026-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega_prevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
