# Generated by Django 6.0.4 on 2026-04-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20)),
                ('descricao', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência')], max_length=30, null=True)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=5, null=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, unique=True)),
                ('status', models.CharField(default='pendente', max_length=30)),
                ('xml', models.TextField(blank=True, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('emitida_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
